import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ALLOWED_HOSTS = ['*']

DEBUG = True

SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 1

SECURE_PROXY_SSL_HEADER = False
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
CSRF_COOKIE_HTTPONLY = False
X_FRAME_OPTIONS = 'DENY'

CORS_ALLOW_CREDENTIALS = False

CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOW_CREDENTIALS = False

# CSRF_TRUSTED_ORIGINS = ['*']

CORS_REPLACE_HTTPS_REFERER = False

CSRF_COOKIE_DOMAIN = ''

CORS_ORIGIN_WHITELIST = ['']

APPEND_SLASH = True
